export default {
  flightNo: 'ET684',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportName: 'BOLE INTL',
  departureTerminal: '2',
  departureTime: '23:00',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'CN',
  arrivalCityName: 'SHANGHAI',
  arrivalAirportName: 'PUDONG INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Asia/Shanghai',
  duration: 705,
  cabin: 'ECONOMY (Y)',
  meal: 'BREAKFAST/MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}