export default {
  flightNo: 'ET809',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportName: 'BOLE INTL',
  departureTerminal: '2',
  departureTime: '08:40',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 325,
  cabin: 'ECONOMY (Y)',
  meal: 'LUNCH',
  equipment: 'AIRBUS INDUSTRIE A350',
}