export default {
  flightNo: 'FA411',
  marketAirlineCode: 'FA',
  marketAirlineName: 'FLYSAFAIR',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'DURBAN',
  departureAirportName: 'KING SHAKA INTL',
  departureTerminal: '',
  departureTime: '06:25',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 70,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'BOEING 737-800',
}