export default {
  flightNo: '4Z554',
  marketAirlineCode: '4Z',
  marketAirlineName: 'Sa Airlink',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'DURBAN',
  departureAirportName: 'KING SHAKA INTL',
  departureTerminal: '',
  departureTime: '08:05',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 65,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'Embraer 190',
}