export default {
  flightNo: 'ET808',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '14:30',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 315,
  cabin: 'ECONOMY (Y)',
  meal: 'MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}