export default {
  flightNo: 'CA868',
  marketAirlineCode: 'CA',
  marketAirlineName: 'AIR CHINA',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'A',
  departureTime: '10:10',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'CN',
  arrivalCityName: 'SHENZHEN',
  arrivalAirportName: 'BAO AN INTL',
  arrivalTerminal: 'T3',
  arrivalTimeZone: 'Asia/Shanghai',
  duration: 765,
  cabin: 'ECONOMY (Y)',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}