export default {
  flightNo: 'ET1820',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: 'SA571',
  operateAirlineCode: 'SA',
  operateAirlineName: 'SOUTH AFRICAN AIRWAYS',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '16:55',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'DURBAN',
  arrivalAirportName: 'KING SHAKA INTL',
  arrivalTerminal: '',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 65,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'AIRBUS A320',
}