export default {
  flightNo: 'ET685',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "CN",
  departureCityName: 'SHANGHAI',
  departureAirportName: 'PUDONG INTL',
  departureTerminal: '2',
  departureTime: '00:20',
  departureTimeZone: 'Asia/Shanghai',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 745,
  cabin: 'ECONOMY (Y)',
  meal: 'BREAKFAST/MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}