export default {
  flightNo: 'CA867',
  marketAirlineCode: 'CA',
  marketAirlineName: 'AIR CHINA',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "CN",
  departureCityName: 'SHENZHEN',
  departureAirportName: 'BAO AN INTL',
  departureTerminal: 'T3',
  departureTime: '00:10',
  departureTimeZone: 'Asia/Shanghai',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'A',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 810,
  cabin: 'ECONOMY (Y)',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}