const ADD_JNB_ET809 = {
  flightNo: 'ET809',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportName: 'BOLE INTL',
  departureTerminal: '2',
  departureTime: '08:40',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 325,
  cabin: 'ECONOMY (Y)',
  meal: 'LUNCH',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const ADD_SHA_ET684 = {
  flightNo: 'ET684',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportName: 'BOLE INTL',
  departureTerminal: '2',
  departureTime: '23:00',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'CN',
  arrivalCityName: 'SHANGHAI',
  arrivalAirportName: 'PUDONG INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Asia/Shanghai',
  duration: 705,
  cabin: 'ECONOMY (Y)',
  meal: 'BREAKFAST/MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const DUR_JNB_4Z554 = {
  flightNo: '4Z554',
  marketAirlineCode: '4Z',
  marketAirlineName: 'Sa Airlink',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'DURBAN',
  departureAirportName: 'KING SHAKA INTL',
  departureTerminal: '',
  departureTime: '08:05',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 65,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'Embraer 190',
}
const DUR_JNB_FA411 = {
  flightNo: 'FA411',
  marketAirlineCode: 'FA',
  marketAirlineName: 'FLYSAFAIR',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'DURBAN',
  departureAirportName: 'KING SHAKA INTL',
  departureTerminal: '',
  departureTime: '06:25',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 70,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'BOEING 737-800',
}
const JNB_ADD_ET808 = {
  flightNo: 'ET808',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '14:30',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 315,
  cabin: 'ECONOMY (Y)',
  meal: 'MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const JNB_DUR_ET1820 = {
  flightNo: 'ET1820',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: 'SA571',
  operateAirlineCode: 'SA',
  operateAirlineName: 'SOUTH AFRICAN AIRWAYS',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '16:55',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'DURBAN',
  arrivalAirportName: 'KING SHAKA INTL',
  arrivalTerminal: '',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 65,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'AIRBUS A320',
}
const JNB_DUR_FA661 = {
  flightNo: 'FA661',
  marketAirlineCode: 'FA',
  marketAirlineName: 'FLYSAFAIR',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '10:25',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'DURBAN',
  arrivalAirportName: 'KING SHAKA INTL',
  arrivalTerminal: '',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 70,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'BOEING 737-800',
}
const JNB_SZX_CA868 = {
  flightNo: 'CA868',
  marketAirlineCode: 'CA',
  marketAirlineName: 'AIR CHINA',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'A',
  departureTime: '10:10',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'CN',
  arrivalCityName: 'SHENZHEN',
  arrivalAirportName: 'BAO AN INTL',
  arrivalTerminal: 'T3',
  arrivalTimeZone: 'Asia/Shanghai',
  duration: 765,
  cabin: 'ECONOMY (Y)',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}
const SHA_ADD_ET685 = {
  flightNo: 'ET685',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "CN",
  departureCityName: 'SHANGHAI',
  departureAirportName: 'PUDONG INTL',
  departureTerminal: '2',
  departureTime: '00:20',
  departureTimeZone: 'Asia/Shanghai',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 745,
  cabin: 'ECONOMY (Y)',
  meal: 'BREAKFAST/MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const SZX_JNB_CA867 = {
  flightNo: 'CA867',
  marketAirlineCode: 'CA',
  marketAirlineName: 'AIR CHINA',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "CN",
  departureCityName: 'SHENZHEN',
  departureAirportName: 'BAO AN INTL',
  departureTerminal: 'T3',
  departureTime: '00:10',
  departureTimeZone: 'Asia/Shanghai',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'A',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 810,
  cabin: 'ECONOMY (Y)',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}
