const ADD_JNB_ET809 = {
  flightNo: 'ET809',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportCode: 'ADD',
  departureAirportName: 'BOLE INTL',
  departureTerminal: '2',
  departureTime: '08:45',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportCode: 'JNB',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'A',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 320,
  cabin: 'ECONOMY (Y)',
  meal: 'LUNCH',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const ADD_SHA_ET684 = {
  flightNo: 'ET684',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportCode: 'ADD',
  departureAirportName: 'BOLE INTL',
  departureTerminal: '2',
  departureTime: '23:00',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'CN',
  arrivalCityName: 'SHANGHAI',
  arrivalAirportCode: 'SHA',
  arrivalAirportName: 'PUDONG INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Asia/Shanghai',
  duration: 705,
  cabin: 'ECONOMY (Y)',
  meal: 'BREAKFAST/MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const DUR_JNB_4Z554 = {
  flightNo: '4Z554',
  marketAirlineCode: '4Z',
  marketAirlineName: 'Sa Airlink',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'DURBAN',
  departureAirportCode: 'DUR',
  departureAirportName: 'KING SHAKA INTL',
  departureTerminal: '',
  departureTime: '08:05',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportCode: 'JNB',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 65,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'Embraer 190',
}
const DUR_JNB_FA411 = {
  flightNo: 'FA411',
  marketAirlineCode: 'FA',
  marketAirlineName: 'FLYSAFAIR',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'DURBAN',
  departureAirportCode: 'DUR',
  departureAirportName: 'KING SHAKA INTL',
  departureTerminal: '',
  departureTime: '06:25',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportCode: 'JNB',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 70,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'BOEING 737-800',
}
const JNB_ADD_ET808 = {
  flightNo: 'ET808',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportCode: 'JNB',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'A',
  departureTime: '14:30',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportCode: 'ADD',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 315,
  cabin: 'ECONOMY (Y)',
  meal: 'MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const JNB_DUR_ET1820 = {
  flightNo: 'ET1820',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: 'SA571',
  operateAirlineCode: 'SA',
  operateAirlineName: 'SOUTH AFRICAN AIRWAYS',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportCode: 'JNB',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '16:55',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'DURBAN',
  arrivalAirportCode: 'DUR',
  arrivalAirportName: 'KING SHAKA INTL',
  arrivalTerminal: '',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 65,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'AIRBUS A320',
}
const JNB_DUR_FA661 = {
  flightNo: 'FA661',
  marketAirlineCode: 'FA',
  marketAirlineName: 'FLYSAFAIR',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportCode: 'JNB',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '10:25',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'DURBAN',
  arrivalAirportCode: 'DUR',
  arrivalAirportName: 'KING SHAKA INTL',
  arrivalTerminal: '',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 70,
  cabin: 'ECONOMY (Y)',
  meal: 'SNACK',
  equipment: 'BOEING 737-800',
}
const JNB_SZX_CA868 = {
  flightNo: 'CA868',
  marketAirlineCode: 'CA',
  marketAirlineName: 'AIR CHINA',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportCode: 'JNB',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'A',
  departureTime: '10:10',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'CN',
  arrivalCityName: 'SHENZHEN',
  arrivalAirportCode: 'SZX',
  arrivalAirportName: 'BAO AN INTL',
  arrivalTerminal: 'T3',
  arrivalTimeZone: 'Asia/Shanghai',
  duration: 800,
  cabin: 'ECONOMY (Y)',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}
const SHA_ADD_ET685 = {
  flightNo: 'ET685',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "CN",
  departureCityName: 'SHANGHAI',
  departureAirportCode: 'SHA',
  departureAirportName: 'PUDONG INTL',
  departureTerminal: '2',
  departureTime: '23:30',
  departureTimeZone: 'Asia/Shanghai',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportCode: 'ADD',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: '2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 700,
  cabin: 'ECONOMY (Y)',
  meal: 'BREAKFAST/MEAL',
  equipment: 'AIRBUS INDUSTRIE A350',
}
const SZX_JNB_CA867 = {
  flightNo: 'CA867',
  marketAirlineCode: 'CA',
  marketAirlineName: 'AIR CHINA',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "CN",
  departureCityName: 'SHENZHEN',
  departureAirportCode: 'SZX',
  departureAirportName: 'BAO AN INTL',
  departureTerminal: 'T3',
  departureTime: '00:10',
  departureTimeZone: 'Asia/Shanghai',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportCode: 'JNB',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'A',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 810,
  cabin: 'ECONOMY (Y)',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}
const LOS_ADD_ET900 = {
  flightNo: 'ET900',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "NGA",
  departureCityName: 'LAGOS',
  departureAirportCode: 'LOS',
  departureAirportName: 'MURTALA MUHAMMED INTL',
  departureTerminal: 'T1I',
  departureTime: '13:40',
  departureTimeZone: 'Africa/Lagos',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportCode: 'ADD',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: 'T2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 320,
  cabin: 'ECONOMY',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350',
}
const ADD_JNB_ET859 = {
  flightNo: 'ET859',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportCode: 'ADD',
  departureAirportName: 'BOLE INTL',
  departureTerminal: 'T2',
  departureTime: '23:30',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportCode: 'JNB',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'A',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 325,
  cabin: 'ECONOMY',
  meal: 'AVAILABLE',
  equipment: 'BOEING 787-9',
}
const JNB_ADD_ET858 = {
  flightNo: 'ET858',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportCode: 'JNB',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'A',
  departureTime: '22:50',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'ET',
  arrivalCityName: 'ADDIS ABABA',
  arrivalAirportCode: 'ADD',
  arrivalAirportName: 'BOLE INTL',
  arrivalTerminal: 'T2',
  arrivalTimeZone: 'Africa/Addis_Ababa',
  duration: 335,
  cabin: 'ECONOMY',
  meal: 'AVAILABLE',
  equipment: 'BOEING 737MAX8',
}
const ADD_LOS_ET901 = {
  flightNo: 'ET901',
  marketAirlineCode: 'ET',
  marketAirlineName: 'ETHIOPIAN AIRLINES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ET",
  departureCityName: 'ADDIS ABABA',
  departureAirportCode: 'ADD',
  departureAirportName: 'BOLE INTL',
  departureTerminal: 'T2',
  departureTime: '09:00',
  departureTimeZone: 'Africa/Addis_Ababa',
  arrivalCountryCode: 'NGA',
  arrivalCityName: 'LAGOS',
  arrivalAirportCode: 'LOS',
  arrivalAirportName: 'MURTALA MUHAMMED INTL',
  arrivalTerminal: 'T1I',
  arrivalTimeZone: 'Africa/Lagos',
  duration: 325,
  cabin: 'ECONOMY',
  meal: 'AVAILABLE',
  equipment: 'AIRBUS A350 XWB',
}
const JNB_DXB_EK764 = {
  flightNo: 'EK764',
  marketAirlineCode: 'EK',
  marketAirlineName: 'EMIRATES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "ZA",
  departureCityName: 'JOHANNESBURG',
  departureAirportCode: 'JNB',
  departureAirportName: 'O.R. TAMBO INTL',
  departureTerminal: 'B',
  departureTime: '18:50',
  departureTimeZone: 'Africa/Johannesburg',
  arrivalCountryCode: 'AE',
  arrivalCityName: 'DUBAI',
  arrivalAirportCode: 'DXB',
  arrivalAirportName: 'DUBAI INTL',
  arrivalTerminal: '3',
  arrivalTimeZone: 'Asia/Dubai',
  duration: 480,
  cabin: 'ECONOMY',
  meal: 'DINNER/BREAKFAST',
  equipment: 'BOEING 777-300ER',
}
const DXB_CMB_EK348 = {
  flightNo: 'EK348',
  marketAirlineCode: 'EK',
  marketAirlineName: 'EMIRATES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "AE",
  departureCityName: 'DUBAI',
  departureAirportCode: 'DXB',
  departureAirportName: 'DUBAI INTL',
  departureTerminal: '3',
  departureTime: '09:50',
  departureTimeZone: 'Asia/Dubai',
  arrivalCountryCode: 'LK',
  arrivalCityName: 'COLOMBO',
  arrivalAirportCode: 'CMB',
  arrivalAirportName: 'BANDARANAIKE INTL',
  arrivalTerminal: '',
  arrivalTimeZone: 'Asia/Colombo',
  duration: 270,
  cabin: 'ECONOMY',
  meal: 'LUNCH',
  equipment: 'BOEING 777-300ER',
}
const CMB_DXB_EK349 = {
  flightNo: 'EK349',
  marketAirlineCode: 'EK',
  marketAirlineName: 'EMIRATES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "LK",
  departureCityName: 'COLOMBO',
  departureAirportCode: 'CMB',
  departureAirportName: 'BANDARANAIKE INTL',
  departureTerminal: '',
  departureTime: '21:15',
  departureTimeZone: 'Asia/Colombo',
  arrivalCountryCode: 'AE',
  arrivalCityName: 'DUBAI',
  arrivalAirportCode: 'DXB',
  arrivalAirportName: 'DUBAI INTL',
  arrivalTerminal: '3',
  arrivalTimeZone: 'Asia/Dubai',
  duration: 270,
  cabin: 'ECONOMY',
  meal: 'DINNER',
  equipment: 'BOEING 777-300ER',
}
const DXB_JNB_EK763 = {
  flightNo: 'EK763',
  marketAirlineCode: 'EK',
  marketAirlineName: 'EMIRATES',
  operateFlightNo: '',
  operateAirlineCode: '',
  operateAirlineName: '',
  departureCountryCode: "AE",
  departureCityName: 'DUBAI',
  departureAirportCode: 'DXB',
  departureAirportName: 'DUBAI INTL',
  departureTerminal: '3',
  departureTime: '03:30',
  departureTimeZone: 'Asia/Dubai',
  arrivalCountryCode: 'ZA',
  arrivalCityName: 'JOHANNESBURG',
  arrivalAirportCode: 'JNB',
  arrivalAirportName: 'O.R. TAMBO INTL',
  arrivalTerminal: 'B',
  arrivalTimeZone: 'Africa/Johannesburg',
  duration: 480,
  cabin: 'ECONOMY',
  meal: 'BREAKFAST',
  equipment: 'BOEING 777-300ER',
}