const SHA_DUR = {
  co2_emissions: '1458.33',
  flightSegments: [
    {
      time: '00:20',
      flights: [
        {
          flightNo: 'ET685',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "CN",
          departureCityName: 'SHANGHAI',
          departureAirportName: 'PUDONG INTL',
          departureTerminal: '2',
          departureTimeZone: 'Asia/Shanghai',
          arrivalCountryCode: 'ET',
          arrivalCityName: 'ADDIS ABABA',
          arrivalAirportName: 'BOLE INTL',
          arrivalTerminal: '2',
          arrivalTimeZone: 'Africa/Addis_Ababa',
          transferDuration: 0,
          duration: 745,
          cabin: 'ECONOMY (Y)',
          meal: 'BREAKFAST/MEAL',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
        {
          flightNo: 'ET809',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ET",
          departureCityName: 'ADDIS ABABA',
          departureAirportName: 'BOLE INTL',
          departureTerminal: '2',
          departureTimeZone: 'Africa/Addis_Ababa',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'JOHANNESBURG',
          arrivalAirportName: 'O.R. TAMBO INTL',
          arrivalTerminal: 'B',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 55,
          duration: 325,
          cabin: 'ECONOMY (Y)',
          meal: 'LUNCH',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
        {
          flightNo: 'ET1820',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: 'SA571',
          operateAirlineCode: 'SA',
          operateAirlineName: 'SOUTH AFRICAN AIRWAYS',
          departureCountryCode: "ZA",
          departureCityName: 'JOHANNESBURG',
          departureAirportName: 'O.R. TAMBO INTL',
          departureTerminal: 'B',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'DURBAN',
          arrivalAirportName: 'KING SHAKA INTL',
          arrivalTerminal: '',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 230,
          duration: 65,
          cabin: 'ECONOMY (Y)',
          meal: 'SNACK',
          equipment: 'AIRBUS A320',
        },
      ],
    },
    {
      time: '08:05',
      flights: [
        {
          flightNo: '4Z554',
          marketAirlineCode: '4Z',
          marketAirlineName: 'Sa Airlink',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'DURBAN',
          departureAirportName: 'KING SHAKA INTL',
          departureTerminal: '',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'JOHANNESBURG',
          arrivalAirportName: 'O.R. TAMBO INTL',
          arrivalTerminal: 'B',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 0,
          duration: 65,
          cabin: 'ECONOMY (Y)',
          meal: 'SNACK',
          equipment: 'Embraer 190',
        },
        {
          flightNo: 'ET808',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'JOHANNESBURG',
          departureAirportName: 'O.R. TAMBO INTL',
          departureTerminal: 'B',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'ET',
          arrivalCityName: 'ADDIS ABABA',
          arrivalAirportName: 'BOLE INTL',
          arrivalTerminal: '2',
          arrivalTimeZone: 'Africa/Addis_Ababa',
          transferDuration: 320,
          duration: 315,
          cabin: 'ECONOMY (Y)',
          meal: 'MEAL',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
        {
          flightNo: 'ET684',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ET",
          departureCityName: 'ADDIS ABABA',
          departureAirportName: 'BOLE INTL',
          departureTerminal: '2',
          departureTimeZone: 'Africa/Addis_Ababa',
          arrivalCountryCode: 'CN',
          arrivalCityName: 'SHANGHAI',
          arrivalAirportName: 'PUDONG INTL',
          arrivalTerminal: '2',
          arrivalTimeZone: 'Asia/Shanghai',
          transferDuration: 135,
          duration: 705,
          cabin: 'ECONOMY (Y)',
          meal: 'BREAKFAST/MEAL',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
      ]
    },
  ]
}

const SHA_JNB = {
  co2_emissions: '1733.82',
  flightSegments: [
    {
      time: '00:20',
      flights: [
        {
          flightNo: 'ET685',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "CN",
          departureCityName: 'SHANGHAI',
          departureAirportName: 'PUDONG INTL',
          departureTerminal: '2',
          departureTimeZone: 'Asia/Shanghai',
          arrivalCountryCode: 'ET',
          arrivalCityName: 'ADDIS ABABA',
          arrivalAirportName: 'BOLE INTL',
          arrivalTerminal: '2',
          arrivalTimeZone: 'Africa/Addis_Ababa',
          transferDuration: 0,
          duration: 745,
          cabin: 'ECONOMY (Y)',
          meal: 'BREAKFAST/MEAL',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
        {
          flightNo: 'ET809',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ET",
          departureCityName: 'ADDIS ABABA',
          departureAirportName: 'BOLE INTL',
          departureTerminal: '2',
          departureTimeZone: 'Africa/Addis_Ababa',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'JOHANNESBURG',
          arrivalAirportName: 'O.R. TAMBO INTL',
          arrivalTerminal: 'B',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 55,
          duration: 325,
          cabin: 'ECONOMY (Y)',
          meal: 'LUNCH',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
      ],
    },
    {
      time: '14:30',
      flights: [
        {
          flightNo: 'ET808',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'JOHANNESBURG',
          departureAirportName: 'O.R. TAMBO INTL',
          departureTerminal: 'B',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'ET',
          arrivalCityName: 'ADDIS ABABA',
          arrivalAirportName: 'BOLE INTL',
          arrivalTerminal: '2',
          arrivalTimeZone: 'Africa/Addis_Ababa',
          transferDuration: 0,
          duration: 315,
          cabin: 'ECONOMY (Y)',
          meal: 'MEAL',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
        {
          flightNo: 'ET684',
          marketAirlineCode: 'ET',
          marketAirlineName: 'ETHIOPIAN AIRLINES',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ET",
          departureCityName: 'ADDIS ABABA',
          departureAirportName: 'BOLE INTL',
          departureTerminal: '2',
          departureTimeZone: 'Africa/Addis_Ababa',
          arrivalCountryCode: 'CN',
          arrivalCityName: 'SHANGHAI',
          arrivalAirportName: 'PUDONG INTL',
          arrivalTerminal: '2',
          arrivalTimeZone: 'Asia/Shanghai',
          transferDuration: 135,
          duration: 705,
          cabin: 'ECONOMY (Y)',
          meal: 'BREAKFAST/MEAL',
          equipment: 'AIRBUS INDUSTRIE A350',
        },
      ]
    },
  ]
}

const SZX_JNB = {
  co2_emissions: '1040.53',
  flightSegments: [
    {
      time: '00:40',
      flights: [
        {
          flightNo: 'CA867',
          marketAirlineCode: 'CA',
          marketAirlineName: 'AIR CHINA',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "CN",
          departureCityName: 'SHENZHEN',
          departureAirportName: 'BAO AN INTL',
          departureTerminal: 'T3',
          departureTimeZone: 'Asia/Shanghai',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'JOHANNESBURG',
          arrivalAirportName: 'O.R. TAMBO INTL',
          arrivalTerminal: 'A',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 0,
          duration: 800,
          cabin: 'ECONOMY (Y)',
          meal: 'AVAILABLE',
          equipment: 'AIRBUS A350-900',
        },
      ],
    },
    {
      time: '10:10',
      flights: [
        {
          flightNo: 'CA868',
          marketAirlineCode: 'CA',
          marketAirlineName: 'AIR CHINA',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'JOHANNESBURG',
          departureAirportName: 'O.R. TAMBO INTL',
          departureTerminal: 'A',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'CN',
          arrivalCityName: 'SHENZHEN',
          arrivalAirportName: 'BAO AN INTL',
          arrivalTerminal: 'T3',
          arrivalTimeZone: 'Asia/Shanghai',
          transferDuration: 0,
          duration: 765,
          cabin: 'ECONOMY (Y)',
          meal: 'AVAILABLE',
          equipment: 'AIRBUS A350-900',
        },
      ]
    },
  ]
}

const SZX_DUR = {
  co2_emissions: '1222.54',
  flightSegments: [
    {
      time: '00:10',
      flights: [
        {
          flightNo: 'CA867',
          marketAirlineCode: 'CA',
          marketAirlineName: 'AIR CHINA',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "CN",
          departureCityName: 'SHENZHEN',
          departureAirportName: 'BAO AN INTL',
          departureTerminal: 'T3',
          departureTimeZone: 'Asia/Shanghai',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'JOHANNESBURG',
          arrivalAirportName: 'O.R. TAMBO INTL',
          arrivalTerminal: 'A',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 0,
          duration: 810,
          cabin: 'ECONOMY (Y)',
          meal: 'AVAILABLE',
          equipment: 'AIRBUS A350 XWB',
        },
        {
          flightNo: 'FA661',
          marketAirlineCode: 'FA',
          marketAirlineName: 'FLYSAFAIR',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'JOHANNESBURG',
          departureAirportName: 'O.R. TAMBO INTL',
          departureTerminal: 'B',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'DURBAN',
          arrivalAirportName: 'KING SHAKA INTL',
          arrivalTerminal: '',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 165,
          duration: 70,
          cabin: 'ECONOMY (Y)',
          meal: 'SNACK',
          equipment: 'BOEING 737-800',
        },
      ],
    },
    {
      time: '06:25',
      flights: [
        {
          flightNo: 'FA411',
          marketAirlineCode: 'FA',
          marketAirlineName: 'FLYSAFAIR',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'DURBAN',
          departureAirportName: 'KING SHAKA INTL',
          departureTerminal: '',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'ZA',
          arrivalCityName: 'JOHANNESBURG',
          arrivalAirportName: 'O.R. TAMBO INTL',
          arrivalTerminal: 'B',
          arrivalTimeZone: 'Africa/Johannesburg',
          transferDuration: 0,
          duration: 70,
          cabin: 'ECONOMY (Y)',
          meal: 'SNACK',
          equipment: 'BOEING 737-800',
        },
        {
          flightNo: 'CA868',
          marketAirlineCode: 'CA',
          marketAirlineName: 'AIR CHINA',
          operateFlightNo: '',
          operateAirlineCode: '',
          operateAirlineName: '',
          departureCountryCode: "ZA",
          departureCityName: 'JOHANNESBURG',
          departureAirportName: 'O.R. TAMBO INTL',
          departureTerminal: 'A',
          departureTimeZone: 'Africa/Johannesburg',
          arrivalCountryCode: 'CN',
          arrivalCityName: 'SHENZHEN',
          arrivalAirportName: 'BAO AN INTL',
          arrivalTerminal: 'T3',
          arrivalTimeZone: 'Asia/Shanghai',
          transferDuration: 155,
          duration: 765,
          cabin: 'ECONOMY (Y)',
          meal: 'AVAILABLE',
          equipment: 'AIRBUS A350 XWB',
        },
      ]
    },
  ]
}

// const Schedules = [SHA_JNB, SHA_JNB, SHA_JNB, SHA_JNB, SHA_JNB, SHA_JNB, SHA_JNB]
// const Schedules = [SHA_DUR, SHA_DUR, SHA_DUR, SHA_DUR, SHA_DUR, SHA_DUR, SHA_DUR]
const Schedules = [SZX_JNB, SZX_JNB, SZX_JNB, SZX_JNB, SZX_JNB, SZX_JNB, SZX_JNB]
// const Schedules = [SZX_DUR, SZX_DUR, SZX_DUR, SZX_DUR, SZX_DUR, SZX_DUR, SZX_DUR]